package context

import (
	"os"
	"path/filepath"
	"strings"
)

// Language detection by extension (lowercase).
var extToLanguage = map[string]string{
	".go":     "Go",
	".py":     "Python",
	".js":     "JavaScript",
	".ts":     "TypeScript",
	".tsx":    "TypeScript",
	".jsx":    "JavaScript",
	".java":   "Java",
	".c":      "C",
	".h":      "C",
	".cpp":    "C++",
	".cc":     "C++",
	".hpp":    "C++",
	".rs":     "Rust",
	".rb":     "Ruby",
	".php":    "PHP",
	".cs":     "C#",
	".swift":  "Swift",
	".kt":     "Kotlin",
	".scala":  "Scala",
	".sh":     "Shell",
	".bash":   "Shell",
	".zsh":    "Shell",
	".md":     "Markdown",
	".json":   "JSON",
	".yaml":   "YAML",
	".yml":    "YAML",
	".toml":   "TOML",
	".html":   "HTML",
	".css":    "CSS",
	".sql":    "SQL",
	".r":      "R",
	".dart":   "Dart",
	".lua":    "Lua",
	".pl":     "Perl",
	".ex":     "Elixir",
	".exs":    "Elixir",
	".erl":    "Erlang",
	".hs":     "Haskell",
	".tf":     "Terraform",
	".vue":    "Vue",
	".svelte": "Svelte",
}

// Relevant source extensions (allowlist). If empty, all non-ignored files are considered.
var relevantExts = map[string]bool{
	".go": true, ".py": true, ".js": true, ".ts": true, ".tsx": true, ".jsx": true,
	".java": true, ".c": true, ".h": true, ".cpp": true, ".cc": true, ".hpp": true,
	".rs": true, ".rb": true, ".php": true, ".cs": true, ".swift": true, ".kt": true,
	".scala": true, ".sh": true, ".md": true, ".json": true, ".yaml": true, ".yml": true,
	".toml": true, ".html": true, ".css": true, ".sql": true, ".dart": true, ".lua": true,
	".vue": true, ".svelte": true, ".ex": true, ".exs": true, ".erl": true, ".hs": true,
	".tf": true,
}

// DetectLanguage returns language name for ext (with dot), or "Other" / "".
func DetectLanguage(ext string) string {
	ext = strings.ToLower(ext)
	if lang, ok := extToLanguage[ext]; ok {
		return lang
	}
	if ext == "" {
		return "Other"
	}
	return "Other"
}

// IsRelevantSource reports whether file should be considered for context.
func IsRelevantSource(path string) bool {
	ext := strings.ToLower(filepath.Ext(path))
	if ext == "" {
		// Files without extension: consider relevant if basename is known (Makefile, Dockerfile)
		base := strings.ToLower(filepath.Base(path))
		if base == "makefile" || base == "dockerfile" || base == "readme" {
			return true
		}
		return false
	}
	return relevantExts[ext]
}

// EstimateTokens estimates token count from size. ~4 bytes per token heuristic.
func EstimateTokens(size int64) int {
	if size <= 0 {
		return 0
	}
	// 4 bytes per token, minimum 1.
	tokens := int(size / 4)
	if tokens == 0 {
		tokens = 1
	}
	return tokens
}

// IsBinaryContent checks for null bytes in sample to detect binary.
func IsBinaryContent(sample []byte) bool {
	for _, b := range sample {
		if b == 0 {
			return true
		}
	}
	return false
}

// Quick check if file is binary by extension or content sample.
// Caller should have already checked extension; this does content peek.
func IsBinaryFileBySample(path string) (bool, error) {
	f, err := os.Open(path)
	if err != nil {
		return false, err
	}
	defer f.Close()
	buf := make([]byte, 8000)
	n, err := f.Read(buf)
	if err != nil && n == 0 {
		return false, nil
	}
	buf = buf[:n]
	return IsBinaryContent(buf), nil
}

// IsGeneratedContent checks for generated header marker in content.
func IsGeneratedContent(sample []byte) bool {
	// Look at first 2KB for generated marker.
	limit := 2048
	if len(sample) > limit {
		sample = sample[:limit]
	}
	lower := strings.ToLower(string(sample))
	markers := []string{
		"code generated",
		"do not edit",
		"auto-generated",
		"generated by",
	}
	for _, m := range markers {
		if strings.Contains(lower, m) {
			return true
		}
	}
	return false
}
